### ISSUE TITLE
Craches in 1.20.2

### ISSUE THREAD

**Issue by MrCookie112** [GravityCY/QuickStore#1]
The mod crashes in version 1.20.2 when sending objects with the V key. PS: I tested with only the necessary mods
![Capture d'écran 2024-06-09 134904](https://github.com/GravityCY/QuickStore/assets/97046342/ccb8bd1f-a239-4dbe-8717-527e8fdd8ddd)

**Comment by GravityCY** [comment]
I might have fixed it but still, just in case, can you please also send the crash log.

Looks like you're on the Modrinth app, so just click on the logs tab, copy the log that includes the crash and I suggest using https://mclo.gs to remove any personal data, and just paste the link here

**Comment by GravityCY** [comment]
Also I'm a lot more active on discord, if you want you can join it here [Discord](https://discord.gg/CfAYy5KDHG)

**Comment by GravityCY** [comment]
Not closing this yet, but I have a feeling I've fixed it, I've uploaded a new version on modrinth and curseforge for 1.20.2-1.20.4, and I'm 99% that was the issue
